version: '3'
services:
  frontend:
    stdin_open: true
    tty: true
    container_name: asr-label-react-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3002:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    entrypoint: /bin/sh