FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN rm -rf /root/.npm
RUN npm cache clean --force

RUN npm install --legacy-peer-deps

# RUN npm config set unsafe-perm true
# RUN npm install --silent

COPY . .

RUN chown -R node /app/node_modules
EXPOSE 8221
# USER node

