version: '3'
services:
  frontend:
    stdin_open: true
    tty: true
    container_name: asr-label-react-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8221:3000"
    volumes:
      - ./:/app
      - /app/node_modules
