FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# RUN npm config set unsafe-perm true
# RUN npm install --silent

COPY . .

RUN chown -R node /app/node_modules

USER node

EXPOSE 3000

CMD [ "npm", "run", "start" ]
