version: '3'
services:
  db:
    image: postgres:11-alpine
    # restart: unless-stopped
    restart: always
    env_file: 
      - .env
    hostname: ${POSTGRES_HOSTNAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data/dump:/tmp/dump
      - ./postgres_data/script:/docker-entrypoint-initdb.d

  server:
    # stdin_open: true
    # tty: true
    env_file: .env
    container_name: backend-fastapi
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app:app --reload --host 0.0.0.0 --port 8000'
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./templates:/code/templates
      - ./static:/code/static
    environment:
      - POSTGRES_CONNECT_STRING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

volumes:
  postgres_data:
  app:
